import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ToastProvider from './Components/toast/toasterProvider';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Product Catalogue Admin",
  description: "Generated by Harshit",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastProvider>
        {children}
        </ToastProvider>
        </body>
    </html>
  );
}
