import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ToastProvider from './components/Toast/toasterProvider'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Product Catalogue App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastProvider>
        {children}
        </ToastProvider>
        </body>
    </html>
  );
}
